# coding: utf-8

"""
Open-Meteo APIs

Open-Meteo offers free weather forecast APIs for open-source developers and non-commercial use. No API key is required.

The version of the OpenAPI document: 1.0
Contact: info@open-meteo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from weather.models.v1_forecast_get400_response import V1ForecastGet400Response


class TestV1ForecastGet400Response(unittest.TestCase):
    """V1ForecastGet400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ForecastGet400Response:
        """Test V1ForecastGet400Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `V1ForecastGet400Response`
        """
        model = V1ForecastGet400Response()
        if include_optional:
            return V1ForecastGet400Response(
                error = True,
                reason = 'Latitude must be in range of -90 to 90°. Given: 300'
            )
        else:
            return V1ForecastGet400Response(
        )
        """

    def testV1ForecastGet400Response(self):
        """Test V1ForecastGet400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
