# coding: utf-8

"""
Open-Meteo APIs

Open-Meteo offers free weather forecast APIs for open-source developers and non-commercial use. No API key is required.

The version of the OpenAPI document: 1.0
Contact: info@open-meteo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from weather.api.weather_forecast_apis_api import WeatherForecastAPIsApi


class TestWeatherForecastAPIsApi(unittest.TestCase):
    """WeatherForecastAPIsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WeatherForecastAPIsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_forecast_get(self) -> None:
        """Test case for v1_forecast_get

        7 day weather forecast for coordinates
        """
        pass


if __name__ == "__main__":
    unittest.main()
