# coding: utf-8

"""
Open-Meteo APIs

Open-Meteo offers free weather forecast APIs for open-source developers and non-commercial use. No API key is required.

The version of the OpenAPI document: 1.0
Contact: info@open-meteo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from weather.models.current_weather import CurrentWeather


class TestCurrentWeather(unittest.TestCase):
    """CurrentWeather unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CurrentWeather:
        """Test CurrentWeather
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CurrentWeather`
        """
        model = CurrentWeather()
        if include_optional:
            return CurrentWeather(
                time = '',
                temperature = 1.337,
                wind_speed = 1.337,
                wind_direction = 1.337,
                weather_code = 56
            )
        else:
            return CurrentWeather(
                time = '',
                temperature = 1.337,
                wind_speed = 1.337,
                wind_direction = 1.337,
                weather_code = 56,
        )
        """

    def testCurrentWeather(self):
        """Test CurrentWeather"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
