"""Weather state machine module generated by beads."""

from enum import IntEnum


class WeatherState(IntEnum):
    """Enumeration of weather states."""

    ERROR = 0
    FETCHING = 1
    INIT = 2
    SUCCESS = 3


class WeatherStateMachine:
    """State machine for managing weather request states."""

    def __init__(self):
        """Initialize the state machine in ERROR state."""
        self._state = WeatherState.ERROR

    @property
    def state(self) -> WeatherState:
        """Get current state."""
        return self._state

    def data_received(self) -> None:
        """Handle data received event."""
        if self._state == WeatherState.FETCHING:
            self._state = WeatherState.SUCCESS

    def request(self) -> None:
        """Handle new request event."""
        if self._state == WeatherState.INIT:
            self._state = WeatherState.FETCHING
        elif self._state == WeatherState.SUCCESS:
            self._state = WeatherState.INIT

    def retry(self) -> None:
        """Handle retry event."""
        if self._state == WeatherState.ERROR:
            self._state = WeatherState.INIT

    def timeout(self) -> None:
        """Handle timeout event."""
        if self._state == WeatherState.FETCHING:
            self._state = WeatherState.ERROR
