name: Linting and Formatting Check
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # Specify the Python version you want to use

      # Step 3: Install uv
      - name: Install uv
        run: pip install uv

      # Step 4: Install dependencies using uv
      - name: Install dependencies
        run: uv sync

      # Step 5: Run flake8 for linting/formatting checks
      - name: Run flake8
        run: |
          make lint
